[tool.mypy]
python_version = "3.10"
warn_unused_configs = true
disallow_untyped_defs = true
ignore_missing_imports = true
exclude = [
    ".*tests.*",
]

[tool.isort]
profile = "black"
sections = "FUTURE,STDLIB,FIRSTPARTY,THIRDPARTY"
default_section = "THIRDPARTY"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning"
]
